#!/bin/bash -e

mkdir -p makeglossariesgui
cp ../dist/* makeglossariesgui
cp ../README makeglossariesgui
cd ../src
tar cvf ../ctan/tmp.tar `git ls-files`
cd ../ctan/
mkdir -p makeglossariesgui/src
tar xvf tmp.tar -C makeglossariesgui/src
rm tmp.tar
mv makeglossariesgui/src/README makeglossariesgui/src/README-src

# remove .gitignore files

find makeglossariesgui -name .gitignore -delete

# remove empty directories

find makeglossariesgui -type d -empty -delete

zip -r makeglossariesgui.zip makeglossariesgui
