#!/bin/bash -e

mkdir -p makeglossariesgui
cp ../dist/* makeglossariesgui
cp ../README makeglossariesgui
mkdir -p doc/support/makeglossariesgui
cp ../dist/*.pdf ../README doc/support/makeglossariesgui
mkdir -p scripts/makeglossariesgui
cp ../dist/*.jar scripts/makeglossariesgui
mkdir -p source/support/makeglossariesgui/src
cd ../src
tar cvf ../ctan/tmp.tar `git ls-files` --exclude=.gitignore
cd ../ctan/
tar xvf tmp.tar -C source/support/makeglossariesgui/src
mkdir -p makeglossariesgui/src
tar xvf tmp.tar -C makeglossariesgui/src
rm tmp.tar
cp ../README source/support/makeglossariesgui
mv source/support/makeglossariesgui/src/README source/support/makeglossariesgui/src/README-src
mv makeglossariesgui/src/README makeglossariesgui/src/README-src
#zip --exclude="*.swp" --exclude="*.gitignore" -r makeglossariesgui.tds.zip source scripts doc
#zip --exclude="*.swp" --exclude="*.gitignore" -r makeglossariesgui.zip makeglossariesgui makeglossariesgui.tds.zip
zip --exclude="*.swp" --exclude="*.gitignore" -r makeglossariesgui.zip makeglossariesgui
